title = "FirstTimeWatching"
baseURL = "https://firsttimewatching.com/"
locale = "en"
disablePathToLower = true
disableKinds = [
  "taxonomy",
  "term",
]
[params]
  dateFormat = ":date_medium"
[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
  [[menus.main]]
    name = "Channels"
    pageRef = "/channels"
    weight = 10
  [[menus.main]]
    name = "Movies"
    pageRef = "/movies"
    weight = 20
  [[menus.main]]
    name = "TV Series"
    pageRef = "/tv-series"
    weight = 30
  [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 50
timeout = 120
